name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci || npm i
      - run: npm run lint || true
      - run: npm --workspace apps/web run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
